name: Gatling Load Test

on:
 workflow_dispatch:
 push:
    branches:
      - feature/gitHubActionsAssignmentThree
      
 pull_request:
    branches:  
      - feature/gitHubActionsAssignmentThree     

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: 8
           
      - name: Build and Test
        run: sbt -v +gatling:test

      - name: Run Gatling Load Test
        run: sbt gatling:test

      - name: Archive Reports
        uses: actions/upload-artifact@v2
        with:
          name: gatling-report
          path: target/gatling/
          retention-days: 30

