name: Amazon Product ID

on:
  workflow_dispatch:
    inputs:
      product_id:
        description: 'Product ID'
        required: true
        default: "B0B3RRWSF6"
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Run Selenium tests
        run: | 
             mvn test -DsearchProductID="${{ github.event.inputs.product_id }}"
